---
title: "Full motor dataset"
author: "David Quesada"
date: "6/10/2020"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Tests and debug

```{r imports}
library(mtDBN)
library(data.table)
library(dbnR)
```

Test and debug chunks for the mtDBN model.

* First, model fitting:

```{r innit}
dt <- data.table::fread("../dataset/pmsm_temperature_data.csv") # 0.5 secs between rows
```

```{r dataset_treatment}
shift_diff_dt <- function(dt, obj_cols, id_col = NULL){
  dt[, (obj_cols) := lapply(.SD, function(x){c(x[1:(length(x)-1)] - x[2:length(x)],NA)}), .SDcols = obj_cols]
  dt <- dt[1:(dim(dt)[1]-1)]
  if(!is.null(id_col))
    dt <- dt[get(id_col) == shift(get(id_col), -1)]
}

size <- 3
id_var <- "profile_id"

dt[, torque := NULL]
dt <- dbnR::reduce_freq(dt, 30, 0.5, id_var)
obj_vars <- c("stator_yoke", "stator_winding", "stator_tooth", "pm")
#dt <- shift_diff_dt(dt, obj_vars, id_col = "profile_id")
plot(ts(dt$pm))
pred_vars <- names(dt)[!(names(dt) %in% obj_vars)]
test_id <- c(65, 72)
dt_train <- dt[!(profile_id %in% test_id)]
dt_test <- dt[profile_id %in% test_id]

f_dt_train <- dbnR::filtered_fold_dt(dt_train, size, id_var)
f_dt_test <- dbnR::filtered_fold_dt(dt_test, size, id_var)
dt_train[, (id_var) := NULL]
dt_test[, (id_var) := NULL]
```

```{r fit_network}
mode <- 2
set.seed(42)
mv <- F
homogen <- T

if(mv){
  obj_vars <- c("pm","stator_tooth", "stator_winding", "stator_yoke")
}else{
  obj_vars <- "pm"
}

if(mode == 1){
  model_net <- dbnR::learn_dbn_struc(dt_train, size, method = "dmmhc", f_dt = f_dt_train)
  model_fit <- dbnR::fit_dbn_params(model_net, f_dt_train)
  model <- mtDBN::mtDBN$new()
  model$fit_model(dt_train, size, method = "dmmhc", obj_var = obj_vars, mv = mv, homogen = homogen, min_ind = 300, max_depth = 6, f_dt = f_dt_train, prune_val = 0.045)
} else{
  # Single dbn model
  print("Single model training.")
  tmp <- Sys.time()
  model_net <- dbnR::learn_dbn_struc(dt_train, size, method = "psoho", f_dt = f_dt_train, n_it = 50, n_ind = 50, gb_cte = 0.5, lb_cte = 0.5, r_probs = c(-0.5, 1.5), v_probs = c(10,65,25))
  model_fit <- dbnR::fit_dbn_params(model_net, f_dt_train)
  print(tmp - Sys.time())
  
  print("----------------------")
  
  # mtDBN model
  print("mtDBN training.")
  tmp <- Sys.time()
  model <- mtDBN::mtDBN$new()
  model$fit_model(dt_train, size, method = "psoho", obj_var = obj_vars, mv = mv, homogen = homogen, min_ind = 300, max_depth = 6, f_dt = f_dt_train, n_it = 50, n_ind = 50, gb_cte = 0.5, lb_cte = 0.5, r_probs = c(-0.5, 1.5), v_probs = c(10,65,25), prune_val = 0.045)
  print(tmp - Sys.time())
  print("Model training finish.")
  
} 

```

* Second, forecasting 

```{r forecasting_all}
obj_vars <- c("pm_t_0", "stator_tooth_t_0", "stator_winding_t_0", "stator_yoke_t_0")
ev_vars <- c("ambient_t_0","coolant_t_0","u_d_t_0","u_q_t_0","motor_speed_t_0","i_d_t_0","i_q_t_0")

res_uni <- NULL
res_mtdbn <- NULL

sink("fore_results.txt")

for(i in f_dt_test_id[, unique(profile_id_t_0)]){
  it <- dim(f_dt_test_id[profile_id_t_0 == i])[1] %/% 100
  rest <- dim(f_dt_test_id[profile_id_t_0 == i])[1] %% 100
  for(j in 1:it){
    print("Forecasting time for single net: ")
    res_net <- dbnR::forecast_ts(f_dt_test, model_fit, size = size, obj_vars = obj_vars, ini = 100*(j-1)+1, len = 100, prov_ev = ev_vars, plot_res = F)
    print("Forecasting time for mtDBN")
    res <- model$forecast_ts(f_dt_test, obj_vars, ini = 100*(j-1)+1, len = 100, prov_ev = ev_vars, plot_res = F)
  }
  print("Forecasting time for single net: ")
  res_net <- dbnR::forecast_ts(f_dt_test, model_fit, size = size, obj_vars = obj_vars, ini = 100*it+1, len = rest, prov_ev = ev_vars, plot_res = F)
  print("Forecasting time for mtDBN")
  res <- model$forecast_ts(f_dt_test, obj_vars, ini = 100*it+1, len = rest, prov_ev = ev_vars, plot_res = F)
}

sink()

file_name <- "./fore_results.txt"
res <- readChar(file_name, file.info(file_name)$size)

digits <- regmatches(res, gregexpr("[[:digit:]]+.[[:digit:]]+", res)) # All decimal numbers
digits <- digits[[1]][-seq(1, length(digits[[1]]), by = 5)] # Disregard the execution times

res <- matrix(data = 0.0, nrow = 2, ncol = length(obj_vars), dimnames = list(c("simple", "mtdbn"), obj_vars))
i_idx <- 0
j_idx <- 0

for(d in digits){
  res[i_idx + 1, j_idx + 1] <- res[i_idx + 1, j_idx + 1] + as.numeric(d)
  j_idx <- (j_idx + 1) %% length(obj_vars)
  if(j_idx == length(obj_vars)-1)
    i_idx <- (i_idx + 1) %% 2
}

res <- res / (length(digits) / (2*length(obj_vars)))
print(res)

```

```{r forecasting, eval=FALSE}
ini <- 301
len <- 400

obj_vars <- c("pm_t_0", "stator_tooth_t_0", "stator_winding_t_0", "stator_yoke_t_0")
ev_vars <- c("ambient_t_0","coolant_t_0","u_d_t_0","u_q_t_0","motor_speed_t_0","i_d_t_0","i_q_t_0")
print("Forecasting time for single net: ")
res_net <- dbnR::forecast_ts(f_dt_test, model_fit, size = size, obj_vars = obj_vars, ini = ini, len = len, prov_ev = ev_vars)

print("----------------------")

print("Forecasting time for mtDBN")
res <- model$forecast_ts(f_dt_test, obj_vars, ini = ini, len = len, prov_ev = ev_vars)

```

